import React, { Component } from "react";

export class HexagonBg extends Component {
  render() {
    return (
      <div className="hexagon-hover-effect">
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
        <div class="row">
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
          <div class="hexagon-home"></div>
        </div>
      </div>
    );
  }
}

export default HexagonBg;
